language: ruby

# to override the --deployment default arg,
# and to exclude debugger gem, which brings in an old version of debugger-ruby_core_source
bundler_args: --no-color --without test

script: "bundle exec rake"

before_install:
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis CI test of cruisecontrolrb"

notifications:
  email:
    on_success: change
    on_failure: always

rvm:
  - 1.8.7
  - 1.9.3
  - rbx

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: jruby-19mode

